input: "read_one.seq.txt.gz"
pair: "read_two.seq.txt.gz"
name: "sample_name"
output: "test_out/bwa_out"
reference: "/scratch/jfv/mak_snp_analysis/ensembl/ce_ws210/genome.fa"
verbose: true
samtools: "/n/site/inst/Linux-x86_64/bioinfo/bin/samtools"
bwa: "/n/projects/jfv/tools/bin/bwa"
picard: "/n/site/inst/Linux-x86_64/bioinfo/picard/picard-tools-1.49"
