reference: "/n/data1/genomes/igenome/Drosophila_melanogaster/UCSC/dm3/Sequence/BWAIndex/genome.fa"
output: "bwa_align/output"
samtools: "/n/local/bin/samtools"
bwa: "/n/local/bin/bwa"
picard: "/n/local/stage/picard/current"
verbose: true
