reference: "/n/data1/genomes/igenome/Drosophila_melanogaster/UCSC/dm3/Sequence/Bowtie2Index/genome.fa"
index: "/n/data1/genomes/igenome/Drosophila_melanogaster/UCSC/dm3/Sequence/Bowtie2Index/genome"
gtf: "/n/data1/genomes/igenome/Drosophila_melanogaster/UCSC/dm3/Annotation/Genes/genes.gtf"
output: "rna_seq_out"
tophat: "/n/local/bin/tophat"
cufflinks: "/n/local/bin/cufflinks"
samtools: "/n/local/bin/samtools"
picard: "/n/local/stage/picard/current"
verbose: true
threads: 2
tophat_params: "-g 1 --mate-inner-dist 200 --mate-std-dev 70 --segment-length 35 --segment-mismatches 2"
